### PR TITLE
Exporting as named export bare test function

### PR DESCRIPTION
**Pull request by Andarist**
**Motivation**
I do not want a singleton object and I just need to benefit from the simple test function, without having to read an object's property.

### CODE REVIEW

**Comment by Andarist** [comment]
@rafrex friendly 🏓

**Comment by rafrex** [comment]
Hi, sorry for the late response.

What are the advantages of exporting a function instead of a singleton?

In looking at your `react-onclickoutside` code I can't see why a singleton wouldn't work. You're saving the test result as `passiveEventSupport` to access each time an instance is created, so why not just access the exported singleton?

I chose to export a singleton because of its reusability (test only needs to run once and the result can be used anywhere), and its single source of truth. If its a function, then the test will need to be run by each module that uses it, which could be many in an app, as well as adding dev overhead to keep track of the result (or rerun the test every time, which is bad).

**Comment by Andarist** [comment]
test's result could be cached (with optional way to invalidate it), i find the implemented API a little bit quirky though and wouldnt like to include it in the current form. Wrapping a single value in an object is excessive and costs few bytes when shipped to the browser in opposed to:
```js
let cached

const testPassiveEventsSupport = force => {
  if (!force && cached !== undefined) {
    return cached
  }
  if (typeof window !== 'undefined' && typeof window.addEventListener === 'function') {
    let passive = false;
    const options = Object.defineProperty({}, 'passive', {
      get() { passive = true; },
    });
    const noop = () => {};
    window.addEventListener('testPassiveEventSupport', noop, options);
    window.removeEventListener('testPassiveEventSupport', noop, options);
    return (cached = passive)
  }
}

export default testPassiveEventsSupport
```

**Comment by rafrex** [comment]
It's an object because it looks like this:
```js
// exported detectPassiveEvents object
{
  hasSupport: true | false,
  update(),
}
```

Your way with with a closure and getter function that optionally takes a force arg for invalidation is good too. You may save a couple of bytes, but not enough to make a difference for me.

The singleton object with an update function is a pattern I use throughout the [`detect-it`](https://github.com/rafrex/detect-it) detections and I've had no issues with it so far. It probably makes more sense when there are multiple values grouped inside an object, but for consistency I think I'm going to keep it the way it is.

**Comment by Andarist** [comment]
> The singleton object with an update function is a pattern I use throughout the detect-it detections and I've had no issues with it so far. It probably makes more sense when there are multiple values grouped inside an object, but for consistency I think I'm going to keep it the way it is.

That's why I was not proposing a rewrite in the PR but just merely an additional export.

**Comment by rafrex** [comment]
I'm sorry but I'm not going to add an additional function export that returns a property from an object that is already exported just because you don't like having to access the object's property. It adds extra bytes and additional complexity to the api.

If there's a use case for why accessing the object's property doesn't work, then I'd consider it.

In your app you can wrap the import in a function and access  the property that way if you prefer.
```js
import detectPassiveEvents from 'detectPassiveEvents';

function testPassiveEventsSupport(force) {
  if (force) detectPassiveEvents.update();
  return detectPassiveEvents.hasSupport;
}
```

**Comment by Andarist** [comment]
Sure, it's understandable. Cheers :)

**Pull request closed without merging**
